package orm;
// Generated Jan 5, 2022 8:39:30 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private String PProuctName;
     private String PBrand;
     private String PDescription;
     private Double PPrice;
     private Double PQty;
     private String PImage;

    public Product() {
    }

    public Product(String PProuctName, String PBrand, String PDescription, Double PPrice, Double PQty, String PImage) {
       this.PProuctName = PProuctName;
       this.PBrand = PBrand;
       this.PDescription = PDescription;
       this.PPrice = PPrice;
       this.PQty = PQty;
       this.PImage = PImage;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPProuctName() {
        return this.PProuctName;
    }
    
    public void setPProuctName(String PProuctName) {
        this.PProuctName = PProuctName;
    }
    public String getPBrand() {
        return this.PBrand;
    }
    
    public void setPBrand(String PBrand) {
        this.PBrand = PBrand;
    }
    public String getPDescription() {
        return this.PDescription;
    }
    
    public void setPDescription(String PDescription) {
        this.PDescription = PDescription;
    }
    public Double getPPrice() {
        return this.PPrice;
    }
    
    public void setPPrice(Double PPrice) {
        this.PPrice = PPrice;
    }
    public Double getPQty() {
        return this.PQty;
    }
    
    public void setPQty(Double PQty) {
        this.PQty = PQty;
    }
    public String getPImage() {
        return this.PImage;
    }
    
    public void setPImage(String PImage) {
        this.PImage = PImage;
    }




}


