package orm;
// Generated Jan 5, 2022 8:39:30 PM by Hibernate Tools 4.3.1



/**
 * UserRegistation generated by hbm2java
 */
public class UserRegistation  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String password;
     private String mobile;
     private String address;
     private String zipCode;

    public UserRegistation() {
    }

    public UserRegistation(String name, String email, String password, String mobile, String address, String zipCode) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.mobile = mobile;
       this.address = address;
       this.zipCode = zipCode;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }




}


